CREATE TABLE users_audit (
    version                  BIGINT       NOT NULL AUTO_INCREMENT,
    id                       CHAR(36)     NOT NULL,
    first_names              VARCHAR(100) NOT NULL,
    last_names               VARCHAR(100) NOT NULL,
    legajo                   VARCHAR(20)  NULL,
    email                    VARCHAR(255) NOT NULL,
    role                     VARCHAR(20)  NOT NULL,
    account_status           VARCHAR(20)  NOT NULL,
    email_verified           BOOLEAN      NOT NULL,
    must_change_password     BOOLEAN      NOT NULL,
    github_username          VARCHAR(100) NULL,
    avatar_ref               VARCHAR(255) NULL,
    first_login              BOOLEAN      NOT NULL,
    guided_tour_completed    BOOLEAN      NOT NULL,
    terms_version_accepted   VARCHAR(20)  NULL,
    terms_accepted_at        DATETIME(6)  NULL,
    created_at               DATETIME(6)  NOT NULL,
    created_user             CHAR(36)     NULL,
    updated_at               DATETIME(6)  NOT NULL,
    last_updated_user        CHAR(36)     NULL,
    deleted_at               DATETIME(6)  NULL,
    lock_version             BIGINT       NOT NULL,
    PRIMARY KEY (version),
    KEY idx_users_audit_id_version (id, version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
